export const colors = {
    // Splash screen and static colors
    white: "#FFFFFF",
    black: "#000000",
    loader: "#0066FF",
    bannerHome: "#203ED6",
    bannerRefer: "#F59300",
    bannerLike: "#9300F5",

    // Theme colors (CCS variables for NativeWind)
    primary: "var(--primary)",
    onPrimary: "var(--on-primary)",
    primaryContainer: "var(--primary-container)",
    onPrimaryContainer: "var(--on-primary-container)",
    secondary: "var(--secondary)",
    onSecondary: "var(--on-secondary)",
    secondaryContainer: "var(--secondary-container)",
    onSecondaryContainer: "var(--on-secondary-container)",
    tertiary: "var(--tertiary)",
    onTertiary: "var(--on-tertiary)",
    tertiaryContainer: "var(--tertiary-container)",
    onTertiaryContainer: "var(--on-tertiary-container)",
    error: "var(--error)",
    onError: "var(--on-error)",
    errorContainer: "var(--error-container)",
    onErrorContainer: "var(--on-error-container)",
    background: "var(--background)",
    onBackground: "var(--on-background)",
    surface: "var(--surface)",
    onSurface: "var(--on-surface)",
    surfaceVariant: "var(--surface-variant)",
    onSurfaceVariant: "var(--on-surface-variant)",
    outline: "var(--outline)",
    outlineVariant: "var(--outline-variant)",
    shadow: "var(--shadow)",
    scrim: "var(--scrim)",
    inverseSurface: "var(--inverse-surface)",
    inverseOnSurface: "var(--inverse-on-surface)",
    inversePrimary: "var(--inverse-primary)",
};

module.exports = { colors };
