apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.devicesecurity'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useExpoPublishing()

android {
  compileSdkVersion 36
  namespace 'expo.modules.devicesecurity'

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.20"
}
